/**
 * Seed script to populate the database with sample properties for development.
 * Run with: npx tsx scripts/seed-properties.ts
 *
 * Requires NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env.local
 */

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(supabaseUrl, supabaseServiceKey);

const SAMPLE_PROPERTIES = [
  {
    source_platform: 'immoscout24',
    source_url: 'https://www.immobilienscout24.de/expose/example-1',
    source_id: 'seed-001',
    title: 'Charmante 3-Zimmer-Altbauwohnung in Prenzlauer Berg',
    price: 349000,
    living_area: 85,
    plot_area: null,
    rooms: 3,
    year_built: 1905,
    property_type: 'wohnung',
    zip_code: '10435',
    city: 'Berlin',
    state: 'berlin',
    description_original: 'Wunderschöne Altbauwohnung mit hohen Decken, Stuck und Dielen. Die Wohnung wurde 2019 kernsaniert und verfügt über eine moderne Einbauküche, ein großes Bad mit Wanne und Dusche sowie einen Balkon zum ruhigen Innenhof.',
    description_ai: 'Diese Altbauperle in Prenzlauer Berg vereint historischen Charme mit modernem Komfort. Hohe Stuckdecken und originale Dielen schaffen eine einzigartige Atmosphäre auf 85m². Die Kernsanierung von 2019 bringt zeitgemäßen Standard: moderne Einbauküche, großzügiges Bad mit Wanne und Dusche. Der Balkon zum ruhigen Innenhof ist dein Rückzugsort mitten in der Stadt. Die Top-Lage bietet alles in Laufweite – Cafés, Parks, ÖPNV. Ein echtes Investment mit Charakter.',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800',
    ],
    is_erbpacht: false,
    is_denkmalschutz: false,
    is_provisionsfrei: true,
    hausgeld: 320,
    energy_data: { type: 'Verbrauchsausweis', value: '98 kWh/(m²·a)', class: 'C' },
    is_active: true,
  },
  {
    source_platform: 'immoscout24',
    source_url: 'https://www.immobilienscout24.de/expose/example-2',
    source_id: 'seed-002',
    title: 'Gepflegtes Einfamilienhaus mit Garten in Potsdam',
    price: 485000,
    living_area: 140,
    plot_area: 600,
    rooms: 5,
    year_built: 1998,
    property_type: 'einfamilienhaus',
    zip_code: '14469',
    city: 'Potsdam',
    state: 'brandenburg',
    description_original: 'Freistehendes Einfamilienhaus in ruhiger Wohnlage. 5 Zimmer, 2 Bäder, Keller, Garage. Großer Südgarten. Gasheizung von 2015.',
    description_ai: 'Dieses gepflegte Einfamilienhaus in Potsdam bietet Familien alles, was das Herz begehrt. Auf 140m² verteilen sich fünf Zimmer und zwei Bäder über zwei Etagen. Der 600m² große Südgarten ist perfekt für Kinder und Grillabende. Die Gasheizung von 2015 sorgt für niedrige Nebenkosten. Keller und Garage runden das Paket ab. Die ruhige Wohnlage und die Nähe zu Berlin machen dieses Objekt zum idealen Zuhause oder zur soliden Kapitalanlage.',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    ],
    is_erbpacht: false,
    is_denkmalschutz: false,
    is_provisionsfrei: false,
    hausgeld: null,
    energy_data: { type: 'Bedarfsausweis', value: '120 kWh/(m²·a)', class: 'D' },
    is_active: true,
  },
  {
    source_platform: 'immowelt',
    source_url: 'https://www.immowelt.de/expose/example-3',
    source_id: 'seed-003',
    title: 'Renditestarkes Mehrfamilienhaus in Leipzig-Plagwitz',
    price: 890000,
    living_area: 450,
    plot_area: 300,
    rooms: 18,
    year_built: 1910,
    property_type: 'mehrfamilienhaus',
    zip_code: '04229',
    city: 'Leipzig',
    state: 'sachsen',
    description_original: '6-Familienhaus, voll vermietet. Jahresnettokaltmiete: 52.000€. Fassade und Dach saniert 2018. 3 Wohnungen modernisiert.',
    description_ai: 'Kapitalanleger aufgepasst: Dieses Mehrfamilienhaus in Leipzig-Plagwitz liefert ab Tag eins. Mit einer Jahresnettokaltmiete von 52.000€ ergibt sich eine Bruttomietrendite von über 5,8%. Das Haus ist voll vermietet, Fassade und Dach wurden 2018 saniert. Drei der sechs Wohnungen sind bereits modernisiert – hier steckt noch Upside-Potenzial. Plagwitz gehört zu den angesagtesten Vierteln Leipzigs mit steigenden Mieten und Kaufpreisen. Ein solides Cashflow-Objekt mit Wertsteigerungspotenzial.',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
      'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    is_erbpacht: false,
    is_denkmalschutz: true,
    is_provisionsfrei: false,
    hausgeld: null,
    energy_data: { type: 'Verbrauchsausweis', value: '145 kWh/(m²·a)', class: 'E' },
    is_active: true,
  },
  {
    source_platform: 'immoscout24',
    source_url: 'https://www.immobilienscout24.de/expose/example-4',
    source_id: 'seed-004',
    title: 'Moderne 2-Zimmer-Wohnung in München-Schwabing',
    price: 420000,
    living_area: 55,
    plot_area: null,
    rooms: 2,
    year_built: 2019,
    property_type: 'wohnung',
    zip_code: '80801',
    city: 'München',
    state: 'bayern',
    description_original: 'Neubauwohnung im 3.OG mit Aufzug. Hochwertige Ausstattung, Fußbodenheizung, Einbauküche, Balkon. TG-Stellplatz inklusive.',
    description_ai: 'Modernes Wohnen im Herzen Schwabings: Diese 2019 erbaute Wohnung überzeugt mit hochwertiger Ausstattung auf 55m². Fußbodenheizung, Einbauküche und ein sonniger Balkon gehören zum Standard. Der TG-Stellplatz ist inklusive – in Schwabing Gold wert. Die erstklassige Lage mit Englischem Garten um die Ecke, exzellenter ÖPNV-Anbindung und dem pulsierenden Stadtteil-Leben macht diese Wohnung zum Premium-Investment. Ideal für Eigenbezug oder als hochwertige Kapitalanlage.',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800',
      'https://images.unsplash.com/photo-1560448204-61dc36dc98c8?w=800',
    ],
    is_erbpacht: false,
    is_denkmalschutz: false,
    is_provisionsfrei: false,
    hausgeld: 280,
    energy_data: { type: 'Bedarfsausweis', value: '45 kWh/(m²·a)', class: 'A' },
    is_active: true,
  },
  {
    source_platform: 'kleinanzeigen',
    source_url: 'https://www.kleinanzeigen.de/expose/example-5',
    source_id: 'seed-005',
    title: 'Sanierungsbedürftiges Fachwerkhaus im Harz',
    price: 89000,
    living_area: 120,
    plot_area: 800,
    rooms: 6,
    year_built: 1880,
    property_type: 'einfamilienhaus',
    zip_code: '38855',
    city: 'Wernigerode',
    state: 'sachsen-anhalt',
    description_original: 'Fachwerkhaus mit viel Potenzial. Dach undicht, Heizung defekt, Bäder müssen erneuert werden. Grundstück mit altem Baumbestand.',
    description_ai: 'Für mutige Investoren mit Vision: Dieses Fachwerkhaus von 1880 in Wernigerode ist ein Rohdiamant. 120m² Wohnfläche auf einem 800m² großen Grundstück mit altem Baumbestand bieten enormes Potenzial. Ja, hier muss Hand angelegt werden – aber zu diesem Preis liegt der m²-Preis bei sensationellen 742€. Der Harz boomt als Tourismusregion, eine Nutzung als Ferienhaus ist denkbar. Fix & Flip oder langfristiges Projekt – die Zahlen können hier richtig spannend werden.',
    images: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
      'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800',
    ],
    is_erbpacht: false,
    is_denkmalschutz: true,
    is_provisionsfrei: true,
    hausgeld: null,
    energy_data: null,
    is_active: true,
  },
  {
    source_platform: 'immoscout24',
    source_url: 'https://www.immobilienscout24.de/expose/example-6',
    source_id: 'seed-006',
    title: 'Penthouse mit Dachterrasse in Hamburg-Eimsbüttel',
    price: 595000,
    living_area: 95,
    plot_area: null,
    rooms: 3,
    year_built: 2015,
    property_type: 'wohnung',
    zip_code: '20255',
    city: 'Hamburg',
    state: 'hamburg',
    description_original: 'Exklusives Penthouse im 5.OG. 40m² Dachterrasse, offener Wohn-/Essbereich, Masterbed mit Ankleide, Gäste-WC. 2 TG-Plätze.',
    description_ai: 'Über den Dächern Hamburgs: Dieses Penthouse in Eimsbüttel ist purer Luxus. Die 40m² Dachterrasse mit Skyline-Blick ist dein privates Outdoor-Wohnzimmer. Innen überzeugen 95m² mit offenem Wohn-/Essbereich, Masterbedroom mit Ankleide und Gäste-WC. Baujahr 2015 bedeutet modernste Technik und niedrige Energiekosten. Zwei TG-Plätze runden das Premium-Paket ab. Eimsbüttel bietet urbanes Leben mit Charme – der perfekte Sweet Spot zwischen Szene und Seriosität.',
    images: [
      'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
      'https://images.unsplash.com/photo-1600573472556-e636c2acda9e?w=800',
    ],
    is_erbpacht: false,
    is_denkmalschutz: false,
    is_provisionsfrei: false,
    hausgeld: 450,
    energy_data: { type: 'Bedarfsausweis', value: '55 kWh/(m²·a)', class: 'B' },
    is_active: true,
  },
  {
    source_platform: 'immowelt',
    source_url: 'https://www.immowelt.de/expose/example-7',
    source_id: 'seed-007',
    title: 'Baugrundstück in Düsseldorf-Oberkassel',
    price: 750000,
    living_area: null,
    plot_area: 450,
    rooms: null,
    year_built: null,
    property_type: 'grundstueck',
    zip_code: '40545',
    city: 'Düsseldorf',
    state: 'nordrhein-westfalen',
    description_original: 'Erschlossenes Baugrundstück in Top-Lage. GFZ 1.2, GRZ 0.4. Baugenehmigung für MFH mit 6 WE liegt vor.',
    description_ai: 'Seltene Gelegenheit in Düsseldorf-Oberkassel: Ein voll erschlossenes Baugrundstück mit 450m² in einer der begehrtesten Lagen der Stadt. Die vorliegende Baugenehmigung für ein Mehrfamilienhaus mit 6 Wohneinheiten macht sofortigen Baubeginn möglich. Bei den aktuellen Oberkasseler Quadratmeterpreisen von 6.000-8.000€ birgt dieses Grundstück enormes Entwicklungspotenzial. GFZ 1.2 und GRZ 0.4 erlauben eine attraktive Ausnutzung. Für Projektentwickler ein echtes Highlight.',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
      'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800',
    ],
    is_erbpacht: false,
    is_denkmalschutz: false,
    is_provisionsfrei: false,
    hausgeld: null,
    energy_data: null,
    is_active: true,
  },
  {
    source_platform: 'immoscout24',
    source_url: 'https://www.immobilienscout24.de/expose/example-8',
    source_id: 'seed-008',
    title: 'Gewerbeeinheit im Frankfurter Nordend',
    price: 280000,
    living_area: 75,
    plot_area: null,
    rooms: 3,
    year_built: 1960,
    property_type: 'gewerbe',
    zip_code: '60318',
    city: 'Frankfurt am Main',
    state: 'hessen',
    description_original: 'Ladenlokal im EG, aktuell als Büro vermietet. Mieteinnahmen 1.200€/Monat kalt. Mietvertrag läuft bis 2028.',
    description_ai: 'Gewerbe-Investment im angesagten Frankfurter Nordend: Dieses Ladenlokal im Erdgeschoss ist aktuell als Büro vermietet und bringt 1.200€ Kaltmiete pro Monat – das entspricht einer Bruttomietrendite von über 5,1%. Der Mietvertrag läuft gesichert bis 2028. Die 75m² in der begehrten Nordend-Lage bieten langfristige Wertstabilität. Auch eine Umnutzung als Gastronomie oder Einzelhandel ist denkbar. Solider Cashflow, minimaler Verwaltungsaufwand.',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800',
    ],
    is_erbpacht: false,
    is_denkmalschutz: false,
    is_provisionsfrei: true,
    hausgeld: 180,
    energy_data: { type: 'Verbrauchsausweis', value: '110 kWh/(m²·a)', class: 'D' },
    is_active: true,
  },
  {
    source_platform: 'kleinanzeigen',
    source_url: 'https://www.kleinanzeigen.de/expose/example-9',
    source_id: 'seed-009',
    title: 'Zwangsversteigerung: 4-Zimmer-ETW in Köln-Ehrenfeld',
    price: 195000,
    living_area: 92,
    plot_area: null,
    rooms: 4,
    year_built: 1975,
    property_type: 'wohnung',
    zip_code: '50823',
    city: 'Köln',
    state: 'nordrhein-westfalen',
    description_original: 'Zwangsversteigerung. Verkehrswert lt. Gutachten: 265.000€. Wohnung im 2.OG, Balkon, Keller. Aktuell leerstehend.',
    description_ai: 'Schnäppchenjäger aufgepasst: Diese 4-Zimmer-Wohnung in Köln-Ehrenfeld kommt als Zwangsversteigerung auf den Markt – deutlich unter dem Verkehrswert von 265.000€. Mit 92m² im beliebten Ehrenfeld bietet die Wohnung enormes Potenzial. Aktuell leerstehend, also sofort beziehbar oder vermietbar. Nach einer Auffrischung sind hier Kaltmieten von 10-12€/m² realistisch. Der Einstiegspreis macht diese Wohnung zum spannendsten Deal der Woche.',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    ],
    is_erbpacht: false,
    is_denkmalschutz: false,
    is_provisionsfrei: true,
    hausgeld: 250,
    energy_data: { type: 'Verbrauchsausweis', value: '135 kWh/(m²·a)', class: 'E' },
    is_active: true,
  },
  {
    source_platform: 'immoscout24',
    source_url: 'https://www.immobilienscout24.de/expose/example-10',
    source_id: 'seed-010',
    title: 'Stilvolle Gründerzeit-Villa in Dresden-Blasewitz',
    price: 1250000,
    living_area: 320,
    plot_area: 1200,
    rooms: 10,
    year_built: 1895,
    property_type: 'einfamilienhaus',
    zip_code: '01279',
    city: 'Dresden',
    state: 'sachsen',
    description_original: 'Denkmalgeschützte Gründerzeitvilla, aufwändig saniert 2012. 10 Zimmer, 3 Bäder, Wintergarten, Parkähnlicher Garten. Steuerliche Vorteile durch Denkmal-AfA.',
    description_ai: 'Ein Juwel der Dresdner Gründerzeit: Diese aufwändig sanierte Villa in Blasewitz ist ein Statement. 320m² Wohnfläche, zehn Zimmer, drei Bäder und ein Wintergarten auf einem parkähnlichen 1.200m² Grundstück. Die Sanierung von 2012 verbindet historische Substanz mit modernem Komfort. Der Clou für Investoren: Als denkmalgeschütztes Gebäude profitierst du von der Denkmal-AfA und erheblichen Steuervorteilen. Blasewitz ist Dresdens Premiumlage am Blauen Wunder. Repräsentativ, wertstabil, einzigartig.',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
    ],
    is_erbpacht: false,
    is_denkmalschutz: true,
    is_provisionsfrei: false,
    hausgeld: null,
    energy_data: { type: 'Bedarfsausweis', value: '95 kWh/(m²·a)', class: 'C' },
    is_active: true,
  },
  {
    source_platform: 'immowelt',
    source_url: 'https://www.immowelt.de/expose/example-11',
    source_id: 'seed-011',
    title: 'Kompakte 1-Zimmer-Wohnung in Nürnberg – Ideal als Kapitalanlage',
    price: 115000,
    living_area: 32,
    plot_area: null,
    rooms: 1,
    year_built: 2005,
    property_type: 'wohnung',
    zip_code: '90459',
    city: 'Nürnberg',
    state: 'bayern',
    description_original: 'Vermietete 1-Zi-Wohnung, Kaltmiete 380€. Aufzug, Stellplatz, Kellerabteil. Guter Zustand.',
    description_ai: 'Der perfekte Einstieg ins Immobilien-Investment: Diese 1-Zimmer-Wohnung in Nürnberg ist bereits vermietet und bringt 380€ Kaltmiete – eine Bruttomietrendite von knapp 4%. Baujahr 2005 bedeutet guter Zustand ohne Sanierungsstau. Aufzug, Stellplatz und Kellerabteil sind inklusive. Bei 115.000€ Kaufpreis und überschaubarem Hausgeld kann hier ein positiver Cashflow gelingen. Ideal als erstes Investment oder zur Portfolio-Ergänzung.',
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
      'https://images.unsplash.com/photo-1489171078254-c3365d6e359f?w=800',
    ],
    is_erbpacht: false,
    is_denkmalschutz: false,
    is_provisionsfrei: false,
    hausgeld: 150,
    energy_data: { type: 'Verbrauchsausweis', value: '78 kWh/(m²·a)', class: 'C' },
    is_active: true,
  },
  {
    source_platform: 'immoscout24',
    source_url: 'https://www.immobilienscout24.de/expose/example-12',
    source_id: 'seed-012',
    title: 'Reihenhaus in Stuttgart-Vaihingen mit Garage',
    price: 520000,
    living_area: 110,
    plot_area: 250,
    rooms: 4,
    year_built: 1985,
    property_type: 'einfamilienhaus',
    zip_code: '70563',
    city: 'Stuttgart',
    state: 'baden-wuerttemberg',
    description_original: 'Reihenendhaus, teilmodernisiert. Neue Fenster 2020, Heizung 2018. Ruhige Sackgasse, gute Anbindung an A8.',
    description_ai: 'Solides Reihenendhaus in Stuttgart-Vaihingen – teilmodernisiert und sofort bezugsfertig. Die 110m² auf vier Zimmer bieten Platz für die ganze Familie. Neue Fenster (2020) und eine moderne Heizung (2018) halten die Nebenkosten im Rahmen. Das 250m² Grundstück mit Garage liegt in einer ruhigen Sackgasse mit direkter A8-Anbindung. Vaihingen profitiert von der Nähe zum Stuttgarter Uni-Campus und Synergiepark – stabile Nachfrage garantiert.',
    images: [
      'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
    ],
    is_erbpacht: false,
    is_denkmalschutz: false,
    is_provisionsfrei: true,
    hausgeld: null,
    energy_data: { type: 'Bedarfsausweis', value: '105 kWh/(m²·a)', class: 'D' },
    is_active: true,
  },
];

async function seed() {
  console.log('Seeding properties...');

  for (const property of SAMPLE_PROPERTIES) {
    const { error } = await supabase
      .from('properties')
      .upsert(property, { onConflict: 'source_platform,source_id' });

    if (error) {
      console.error(`Error seeding ${property.source_id}:`, error.message);
    } else {
      console.log(`Seeded: ${property.title}`);
    }
  }

  console.log('Done! Seeded', SAMPLE_PROPERTIES.length, 'properties.');
}

seed().catch(console.error);
